import "./globals.css";
import { Barlow_Semi_Condensed } from "next/font/google";
import { Header } from "~/components";
import ReduxProvider from "~/providers/redux";

const barlow = Barlow_Semi_Condensed({
  weight: ["600", "700"],
  subsets: ["latin"],
  variable: "--font-barlow",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${barlow.className} h-screen flex justify-center py-8`}>
        <ReduxProvider>
          <main className="w-full max-w-[1366px] flex items-center flex-col gap-12">
            <Header />
            {children}
          </main>
        </ReduxProvider>
      </body>
    </html>
  );
}
